Team-TenTen/LinkHub-BE

.github/workflows/deploy.yml
Dockerfile
build.gradle
deploy.sh
docker-compose.yml
nginx.conf
src/main/resources/application.yml

최초 docker-compose를 통한 nginx + green/blue 서버 실행
develop에 푸쉬 될 경우, GitHub Action => .jar 빌드 => Docker Hub 이미지 업로드 => EC2 접근 => Docker Hub 이미지 다운로드 => green/blue 중 놀고 있는 서버를 닫아버리고 새로운 이미지로 갈아 끼운 후 실행 => Nginx가 새로운 이미지를 바라보도록 변경

Feat/cicd-greenblue 무중단 배포 및 자동화

---

src/main/java/com/tenten/linkhub/domain/space/controller/SpaceController.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/space/SpaceCreateApiRequest.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/space/SpaceDetailGetByIdApiResponse.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/space/SpaceUpdateApiRequest.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/space/SpaceUpdateApiResponse.java
src/main/java/com/tenten/linkhub/domain/space/controller/mapper/SpaceApiMapper.java
src/main/java/com/tenten/linkhub/domain/space/facade/SpaceFacade.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/SpaceDetailGetByIdFacadeRequest.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/SpaceDetailGetByIdFacadeResponse.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/SpaceUpdateFacadeRequest.java
src/main/java/com/tenten/linkhub/domain/space/facade/mapper/SpaceFacadeMapper.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Space.java
src/main/java/com/tenten/linkhub/domain/space/model/space/dto/SpaceUpdateDto.java
src/main/java/com/tenten/linkhub/domain/space/repository/space/SpaceJpaRepository.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultSpaceService.java
src/main/java/com/tenten/linkhub/domain/space/service/SpaceService.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/space/SpaceUpdateRequest.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/space/SpaceWithSpaceImageAndSpaceMemberInfo.java
src/main/java/com/tenten/linkhub/domain/space/service/mapper/SpaceMapper.java
src/main/java/com/tenten/linkhub/global/exception/GlobalApiExceptionHandler.java
src/main/java/com/tenten/linkhub/global/exception/UnauthorizedAccessException.java
src/main/java/com/tenten/linkhub/global/util/CommonValidator.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceFacadeTest.java

#34 
- 스페이스 정보 수정 API 구현
- 스페이스 정보 수정 테스트 작성

Feat/update space/yyw  -  스페이스 정보 수정 API

---

src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberInfos.java
src/main/java/com/tenten/linkhub/domain/space/controller/SpaceController.java
src/main/java/com/tenten/linkhub/domain/space/facade/SpaceFacade.java
src/main/java/com/tenten/linkhub/domain/space/handler/SpaceEventHandler.java
src/main/java/com/tenten/linkhub/domain/space/handler/dto/SpaceImagesDeleteDto.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Space.java
src/main/java/com/tenten/linkhub/domain/space/model/space/SpaceImage.java
src/main/java/com/tenten/linkhub/domain/space/model/space/SpaceMember.java
src/main/java/com/tenten/linkhub/domain/space/model/space/vo/SpaceImages.java
src/main/java/com/tenten/linkhub/domain/space/model/space/vo/SpaceMembers.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultSpaceService.java
src/main/java/com/tenten/linkhub/domain/space/service/SpaceService.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/space/DeletedSpaceImageNames.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/space/SpaceWithSpaceImageAndSpaceMemberInfo.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/space/SpacesFindByQueryResponses.java
src/main/java/com/tenten/linkhub/global/aws/s3/DefaultS3Uploader.java
src/main/java/com/tenten/linkhub/global/aws/s3/S3Uploader.java
src/main/java/com/tenten/linkhub/global/config/SwaggerConfig.java
src/main/java/com/tenten/linkhub/global/exception/GlobalApiExceptionHandler.java
src/main/java/com/tenten/linkhub/global/exception/MaxImageCountExceededException.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceFacadeTest.java

#33 
- 스페이스 삭제 API 구현
- 스페이스 삭제 테스트 작성
- SpaceImage 및 SpaceMember 기존의 기회했던대로 소프트 딜리트 정책 적용
- 소프트 딜리트 적용에 따라 관련 코드들 수정
- SpaceImage 및 SpaceMember에 누락되었던 소프트 딜리트를 적용함에 따라 코드가 일부 많이 변경 되었습니다.
따라서 Space관련 API를 구현하게 된다면 이 PR이 머지된 후 풀 땡기고 진행하시면 좀 더 원활한 작업이 될 것 같습니다.

Feat/delete space/yyw  -  스페이스 삭제 API

---

src/main/java/com/tenten/linkhub/domain/space/controller/dto/space/SpaceDetailGetByIdApiResponse.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/SpaceDetailGetByIdFacadeResponse.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Favorite.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Space.java
src/main/java/com/tenten/linkhub/domain/space/model/space/SpaceMember.java
src/main/java/com/tenten/linkhub/domain/space/model/space/vo/SpaceMembers.java
src/main/java/com/tenten/linkhub/domain/space/repository/favorite/DefaultFavoriteRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/favorite/FavoriteJpaRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/favorite/FavoriteRepository.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultSpaceService.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/space/SpaceWithSpaceImageAndSpaceMemberInfo.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceFacadeTest.java

#89 
- 스페이스 상세 조회 시 스페이스 내의 링크들 수정권한 갖고 있는지에 대한 필드 추가, 해당 스페이스 즐겨찾기 중인지에 대한 필드 추가.
- 해당 테스트에 검증값 추가.

Fix/get space detail by id/yyw  -  스페이스 상세 조회 API 수정

---

src/main/java/com/tenten/linkhub/domain/space/model/space/Space.java
src/test/java/com/tenten/linkhub/domain/space/facade/LinkFacadeTest.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceFacadeTest.java
src/test/java/com/tenten/linkhub/domain/space/service/DefaultLinkServiceTest.java

- 스페이스 수정 API 에러 해결.
- 에러 발생한 테스트 코드 케이스 추가.

Hotfix/update space/yyw  -  스페이스 수정 API 에러 해결.

---

src/main/java/com/tenten/linkhub/domain/member/controller/MemberController.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MemberFollowCreateApiResponse.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MemberProfileApiResponse.java
src/main/java/com/tenten/linkhub/domain/member/repository/follow/FollowJpaRepository.java
src/main/java/com/tenten/linkhub/domain/member/service/MemberServiceImpl.java
src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberFollowCreateResponse.java
src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberProfileResponse.java
src/test/java/com/tenten/linkhub/domain/member/service/MemberServiceTest.java

-  프로필 조회 수정 권한 및 팔로잉 유무 리턴하도록 수정

Fix/member 프로필 조회 수정 권한 및 팔로잉 유무 리턴하도록 수정

---

src/main/java/com/tenten/linkhub/domain/space/controller/SpaceController.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/comment/RepliesFindApiResponse.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/comment/RepliesFindApiResponses.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/comment/RootCommentFindApiResponse.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/comment/RootCommentFindApiResponses.java
src/main/java/com/tenten/linkhub/domain/space/facade/CommentFacade.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/CommentAndChildCountAndMemberInfo.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/CommentAndChildCountAndMemberInfoResponses.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/RepliesAndMemberInfo.java
src/main/java/com/tenten/linkhub/domain/space/facade/dto/RepliesAndMemberInfoResponses.java
src/main/java/com/tenten/linkhub/domain/space/service/CommentService.java
src/test/java/com/tenten/linkhub/domain/space/facade/CommentFacadeTest.java

- 댓글 및 대댓글 페이징 조회시 수정 가능 여부 리턴

Fix/comment 댓글 및 대댓글 페이징 조회시 수정 가능 여부 리턴

---

src/main/java/com/tenten/linkhub/domain/space/controller/LinkController.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultLinkService.java
src/test/java/com/tenten/linkhub/domain/space/facade/LinkFacadeTest.java

- 좋아요 취소시 없으면 익셉션을 보내도록 변경하였습니다.

Fix/Like 존재하지 않는 좋아요 취소 시 진행되는 문제 수정

---

src/main/java/com/tenten/linkhub/domain/member/controller/MemberController.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MemberUpdateApiRequest.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MemberUpdateApiResponse.java
src/main/java/com/tenten/linkhub/domain/member/controller/mapper/MemberApiMapper.java
src/main/java/com/tenten/linkhub/domain/member/model/Member.java
src/main/java/com/tenten/linkhub/domain/member/model/ProfileImage.java
src/main/java/com/tenten/linkhub/domain/member/model/vo/FavoriteCategories.java
src/main/java/com/tenten/linkhub/domain/member/model/vo/ProfileImages.java
src/main/java/com/tenten/linkhub/domain/member/service/MemberService.java
src/main/java/com/tenten/linkhub/domain/member/service/MemberServiceImpl.java
src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberUpdateRequest.java
src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberUpdateResponse.java
src/test/java/com/tenten/linkhub/domain/member/service/MemberServiceTest.java

- 프로필 사진 카테고리를 포함한 멤버 수정 기능입니다.

[Feat]: 프로필 사진, 카테고리를 포함한 멤버 수정 기능 구현

---

src/main/java/com/tenten/linkhub/domain/space/controller/SpaceController.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/spacemember/SpaceMemberRoleChangeApiRequest.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/spacemember/SpaceMemberRoleChangeApiResponse.java
src/main/java/com/tenten/linkhub/domain/space/controller/mapper/SpaceApiMapper.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Space.java
src/main/java/com/tenten/linkhub/domain/space/model/space/SpaceMember.java
src/main/java/com/tenten/linkhub/domain/space/model/space/dto/SpaceMemberRole.java
src/main/java/com/tenten/linkhub/domain/space/model/space/vo/SpaceMembers.java
src/main/java/com/tenten/linkhub/domain/space/repository/favorite/query/FavoriteQueryRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/space/query/SpaceQueryRepository.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultSpaceService.java
src/main/java/com/tenten/linkhub/domain/space/service/SpaceService.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/spacemember/SpaceMemberRoleChangeRequest.java
src/test/java/com/tenten/linkhub/domain/space/service/DefaultSpaceServiceTest.java

#113 
- 스페이스 멤버 권한 수정 API
- 해당 API 테스트
- 나의 즐겨찾기 스페이스 검색 시 정렬 조건 생성일 기준 최신순으로 변경
- 특정 멤버 스페이스 검색 시 정렬 조건 생성일 기준 최신순으로 변경

Feat/change space member role/yyw  -  스페이스 멤버 권한 수정 API

---

src/main/java/com/tenten/linkhub/domain/space/model/space/vo/SpaceMembers.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/querydsl/LinkQueryDslRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/tag/DefaultJpaRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/tag/TagRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/tag/query/TagQueryRepository.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultLinkService.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultSpaceService.java

fix: SpaceMembers 내 메소드 수정

---

src/main/java/com/tenten/linkhub/domain/member/controller/MemberController.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MemberSearchApiRequest.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MemberSearchApiResponse.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MemberSearchApiResponses.java
src/main/java/com/tenten/linkhub/domain/member/controller/mapper/MemberApiMapper.java
src/main/java/com/tenten/linkhub/domain/member/model/Member.java
src/main/java/com/tenten/linkhub/domain/member/model/ProfileImage.java
src/main/java/com/tenten/linkhub/domain/member/model/vo/FavoriteCategories.java
src/main/java/com/tenten/linkhub/domain/member/model/vo/ProfileImages.java
src/main/java/com/tenten/linkhub/domain/member/repository/dto/MemberSearchQueryCondition.java
src/main/java/com/tenten/linkhub/domain/member/repository/dto/MemberWithProfileImageAndFollowingStatus.java
src/main/java/com/tenten/linkhub/domain/member/repository/follow/FollowJpaRepository.java
src/main/java/com/tenten/linkhub/domain/member/repository/member/DefaultMemberRepository.java
src/main/java/com/tenten/linkhub/domain/member/repository/member/MemberJpaRepository.java
src/main/java/com/tenten/linkhub/domain/member/repository/member/MemberRepository.java
src/main/java/com/tenten/linkhub/domain/member/repository/query/MemberQueryRepository.java
src/main/java/com/tenten/linkhub/domain/member/service/MemberService.java
src/main/java/com/tenten/linkhub/domain/member/service/MemberServiceImpl.java
src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberSearchRequest.java
src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberSearchResponse.java
src/main/java/com/tenten/linkhub/domain/member/service/dto/MemberSearchResponses.java
src/main/java/com/tenten/linkhub/domain/member/service/mapper/MemberMapper.java
src/test/java/com/tenten/linkhub/domain/member/service/MemberServiceTest.java
src/test/java/com/tenten/linkhub/domain/space/facade/CommentFacadeTest.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceFacadeTest.java
src/test/java/com/tenten/linkhub/domain/space/service/DefaultSpaceServiceTest.java

- 멤버 검색 기능을 구현하였습니다. (keyword%)

Feat/memberSearch 멤버 검색 기능 구현

---

src/main/java/com/tenten/linkhub/domain/auth/config/SecurityConfig.java
src/main/java/com/tenten/linkhub/domain/notification/model/Notification.java
src/main/java/com/tenten/linkhub/domain/notification/repository/DefaultNotificationRepository.java
src/main/java/com/tenten/linkhub/domain/notification/repository/NotificationJpaRepository.java
src/main/java/com/tenten/linkhub/domain/notification/repository/NotificationRepository.java
src/main/java/com/tenten/linkhub/domain/notification/service/NotificationService.java
src/main/java/com/tenten/linkhub/domain/space/controller/SpaceInvitationController.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/invitation/SpaceInvitationAcceptApiRequest.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/invitation/SpaceInvitationAcceptApiResponse.java
src/main/java/com/tenten/linkhub/domain/space/controller/mapper/SpaceInvitationApiMapper.java
src/main/java/com/tenten/linkhub/domain/space/facade/SpaceInvitationFacade.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Invitation.java
src/main/java/com/tenten/linkhub/domain/space/repository/invitation/DefaultInvitationRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/invitation/InvitationJpaRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/invitation/InvitationRepository.java
src/main/java/com/tenten/linkhub/domain/space/service/SpaceInvitationService.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/invitation/SpaceInvitationAcceptRequest.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceInvitationFacadeTest.java

#42 
- 스페이스 초대 수락 API.
- 스페이스 초대 수락 테스트 코드 작성.
- 해당 엔드포인트 필터 추가.

Feat/accept space invitation/yyw  -  스페이스 초대 수락 API

---

src/main/java/com/tenten/linkhub/domain/notification/controller/dto/SpaceInviteNotificationGetApiRequest.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/LinkRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/dto/PopularLinkGetDto.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/querydsl/LinkQueryDslRepository.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultLinkService.java
src/main/java/com/tenten/linkhub/domain/space/service/dto/link/PopularLinksGetByQueryResponses.java

Hotfix/get links,tags - 링크 조회 및 스웨거 코드 수정

---

src/main/java/com/tenten/linkhub/domain/member/repository/member/DefaultMemberRepository.java
src/main/java/com/tenten/linkhub/domain/member/repository/member/MemberJpaRepository.java
src/main/java/com/tenten/linkhub/domain/member/service/MemberServiceImpl.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Scrap.java
src/main/java/com/tenten/linkhub/domain/space/model/space/vo/SpaceMembers.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultLinkService.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultSpaceService.java
src/main/java/com/tenten/linkhub/global/exception/GlobalApiExceptionHandler.java
src/main/java/com/tenten/linkhub/global/exception/PolicyViolationException.java
src/main/java/com/tenten/linkhub/global/response/ErrorCode.java
src/main/java/com/tenten/linkhub/global/response/ErrorWithDetailCodeResponse.java
src/test/java/com/tenten/linkhub/domain/member/service/MemberServiceTest.java
src/test/java/com/tenten/linkhub/domain/space/facade/LinkFacadeTest.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceFacadeTest.java
src/test/java/com/tenten/linkhub/domain/space/facade/SpaceInvitationFacadeTest.java
src/test/java/com/tenten/linkhub/domain/space/service/DefaultSpaceServiceTest.java

#161 
- 프로젝트 전체적인 Exception 정리.
- 적절하지 못한 예외 적절한 예외로 변경 및 테스트 코드 수정.
- 적절한 새로운 예외 PolicyViolationException 추가.
- 해당 리펙토링 내용은 제 주관적인 시각이 많이 반영됐으므로 추가 안건사항이 있으시면 말씀해주시길 바랍니다.

Refactor/exception response/yyw  -  프로젝트 전체적인 Exception 정리 (1차)

---

src/main/java/com/tenten/linkhub/domain/space/controller/SpaceController.java
src/main/java/com/tenten/linkhub/domain/space/controller/SpaceInvitationController.java

- SpaceController 스웨거 리펙토링.
- SpaceInvitationController 스웨거 리펙토링.

Refactor/swagger/space. -  스웨거 스페이스 관련 컨트롤러 리펙토링

---

src/main/java/com/tenten/linkhub/domain/notification/repository/querydsl/NotificationQueryDslRepository.java

- LEFT JOIN을 이용하는 방식으로 쿼리를 수정했습니다.

Hotfix/get notifications - 알림 조회 API 수정

---

src/main/java/com/tenten/linkhub/domain/space/repository/comment/CommentJpaRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/comment/query/CommentQueryRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/LinkJdbcRepository.java

##작업한 일
- 스페이스 가져오기 시 링크들의 likeCount 0으로 초기화.
- 댓글 굉장히 빠르게 연속으로 작성할 시 조회에서 정렬이 이상하게 됐던 이슈 해결.

Fix/yyw  -  1차 QA 이슈 처리

---

src/main/java/com/tenten/linkhub/domain/member/controller/dto/MailSendApiRequest.java
src/main/java/com/tenten/linkhub/domain/member/controller/dto/MailVerificationApiRequest.java
src/main/java/com/tenten/linkhub/domain/notification/repository/querydsl/NotificationQueryDslRepository.java
src/main/java/com/tenten/linkhub/domain/space/controller/dto/invitation/SpaceInvitationApiRequest.java

- 이메일 발송 API에 validation 메시지 추가
- 이메일 인증 API에 validation 메시지 추가
- 스페이스 초대 API에 validation 메시지 추가

Hotfix/email validation - 이메일 validation message 수정

---

src/main/java/com/tenten/linkhub/domain/auth/config/SecurityConfig.java
src/main/java/com/tenten/linkhub/domain/notification/controller/NotificationController.java
src/main/java/com/tenten/linkhub/domain/notification/controller/dto/UncheckedNotificationsCountApiResponse.java
src/main/java/com/tenten/linkhub/domain/notification/repository/DefaultNotificationRepository.java
src/main/java/com/tenten/linkhub/domain/notification/repository/NotificationJpaRepository.java
src/main/java/com/tenten/linkhub/domain/notification/repository/NotificationRepository.java
src/main/java/com/tenten/linkhub/domain/notification/service/NotificationService.java
src/test/java/com/tenten/linkhub/domain/notification/service/NotificationServiceTest.java
src/test/java/com/tenten/linkhub/domain/space/facade/CommentFacadeTest.java

#174 
- 체크하지 않은 알림 개수 카운팅 API
- 해당 api 테스트 작성.
- 통과하지 않은 테스트 코드 수정 (댓글 페이징 조회 부분)

Feat/count unchecked notifications/yyw  -  체크하지 않은 알림 개수 카운팅 API

---

src/main/java/com/tenten/linkhub/domain/space/controller/SpaceInvitationController.java

[Docs] : 주석 수정

---

src/main/java/com/tenten/linkhub/domain/space/service/SpaceImageUploader.java

[Fix]: 스페이스 디폴트 이미지 변경.

---

src/main/java/com/tenten/linkhub/domain/auth/OAuth2SuccessHandler.java

[Fix] : 로그인 리다이렉션 수정

---

build.gradle
src/main/java/com/tenten/linkhub/domain/space/facade/LinkFacade.java
src/main/java/com/tenten/linkhub/domain/space/handler/LinkEventHandler.java
src/main/java/com/tenten/linkhub/domain/space/model/link/Link.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/DefaultLinkRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/LinkJpaRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/LinkRepository.java
src/test/java/com/tenten/linkhub/domain/space/service/LikeServiceTest.java
src/test/resources/sql/clean_up.sql

- **링크 좋아요, 좋아요 취소 API 수정** 
- **동시성 테스트 코드 작성**
- **테스트 작성 후 데이터 삭제하는 sql 코드 추가**

Hotfix/change redirect url - 링크 좋아요 API 수정

---

src/main/java/com/tenten/linkhub/domain/space/controller/SpaceInvitationController.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

- logback-spring.xml 추가.
- prod 환경에선 loki 서버에 warn 및 error레벨 로그 발생시 해당 로그 전송하게끔 설정함.
- 해당 로그백 파일에서 필요한 변수값 application.yml에 추가.

[Chore]: logback-spring.xml 추가 및 application.yml에 필요한 환경변수 추가.

---

build.gradle

- 로키 어펜더 관련 의존성 누락으로 인한 로그백 에러 해결.

Fix/logback - 로그백 관련 에러 해결.

---

build.gradle
src/main/java/com/tenten/linkhub/domain/space/controller/dto/space/SpaceCreateApiRequest.java
src/main/java/com/tenten/linkhub/domain/space/model/link/Link.java
src/main/java/com/tenten/linkhub/domain/space/model/space/Space.java
src/main/java/com/tenten/linkhub/domain/space/model/space/SpaceMember.java
src/main/java/com/tenten/linkhub/domain/space/repository/link/LinkJdbcRepository.java
src/main/java/com/tenten/linkhub/domain/space/repository/space/querydsl/DynamicQueryFactory.java
src/main/java/com/tenten/linkhub/domain/space/service/DefaultSpaceService.java
src/main/java/com/tenten/linkhub/global/CustomFunctionContributor.java
src/main/java/com/tenten/linkhub/global/util/CommonValidator.java
src/main/java/com/tenten/linkhub/global/util/SearchKeywordParser.java
src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
src/main/resources/application.yml
src/main/resources/db/migration/V1__init.sql
src/test/java/com/tenten/linkhub/domain/space/service/DefaultSpaceServiceTest.java
src/test/resources/sql/clean_up.sql
src/test/resources/sql/test-schema.sql

##작업한 일
- 스페이스 검색에 mysql full text search 도입
- 테스트 코드 일부 수정
- 키워드를 그대로 사용하지 않고 파싱하여 사용하는 방식을 통해 최적화.
- flyway 도입

Fix/search. -  mysql full text search 도입 및 flyway 도입.

---

src/main/java/com/tenten/linkhub/domain/space/controller/dto/space/PublicSpacesFindWithFilterApiRequest.java
src/main/java/com/tenten/linkhub/domain/space/repository/common/mapper/RepositoryDtoMapper.java
src/main/java/com/tenten/linkhub/domain/space/repository/space/querydsl/SpaceQueryDslRepository.java
src/test/java/com/tenten/linkhub/domain/space/service/DefaultSpaceServiceTest.java

Fix/space/pagination  -  스페이스 필터 조회 API NPE 해결.

---

src/main/java/com/tenten/linkhub/domain/space/common/SpaceCursorPageRequest.java

- 스페이스 필터 조회API pageSize 10으로 요청 시 11개 반환하는 에러 해결.

Fix/space/pagination  -  스페이스 필터 조회 API 에러 해결.

---

README.md

기능 시연 부분 댓글 내용 추가, 기능 시연 부분 gif 크기 조절
댓글 항목 설명 수정.

[Docs]: 리드미 업데이트
